### ISSUE TITLE
Plugin will not load on v0.12.12

### ISSUE THREAD

**Issue by PJJPtx** [dgarrett/phone-to-roam-to-obsidian#1]
I copied the files to my .obsidian/plugins/phone-to-roam/ folder, but I get an error when trying to turn it in "Plugin failed to load..."

Maybe it's the new Obsidian release?

**Comment by dgarrett** [comment]
Which files did you copy? You need to copy main.js and manifest.json from the [latest plugin release](https://github.com/dgarrett/phone-to-roam-to-obsidian/releases)

The git repository only contains the uncompiled .ts source.
