### ISSUE TITLE
endless note append

### ISSUE THREAD

**Issue by cyberat0r** [dgarrett/phone-to-roam-to-obsidian#3]
hi i'm not sure if this is still maintained but i haven't been able to figure this out

the plugin reads and appends the notes to my daily note just fine. however, it doesnt stop. every so often, it'll append the same text to the daily note of the day it was sent. leading to this:
![image](https://github.com/dgarrett/phone-to-roam-to-obsidian/assets/137528046/ab0d314e-cf4c-4ee0-a613-0c330d383420)

if there's anyway to fix it, please lmk. it's a brilliant plugin, and this is the only issue i've found with it.

**Comment by dgarrett** [comment]
Hi @cyberat0r, I haven't worked on this in a while, but I think I know what the issue is. I'm not going through and marking messages as synced with a PATCH to `https://app.phonetonote.com/feed/${ptnId}.json` with 
```json
{
    roam_key: $ptnKey,
    status: 'synced'
}
```

I'll try to update this sometime this week.

**Comment by dgarrett** [comment]
This should be fixed in the latest update (1.0.2). Let me know if it works out for you.

**Comment by cyberat0r** [comment]
it works perfectly, thank you so much!! now i can hopefully fix another plugin that aint workin right since i think it's due to something while syncing it to mobile. thanks again!!
